### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by casio** [vue-styleguidist/vue-cli-plugin-styleguidist#14]
Using a vue-cli 3.03 generated vanilla project and this repo as the first plugin.
Starting the styleguide task will show below warning, start the server but without showing `AppButton` docs.

`Warning: Cannot parse src/components/AppButton.vue: TypeError: Cannot read property 'default' of undefined`

This seems related to the import in the example component - when you remove `sizeMixin` the docs will be rendered just fine. I guess that is related to a missing webpack/babel config - have an idea?

**Comment by DanielPe05** [comment]
Any ideas what could be causing this? I'm seeing the same exact thing

**Comment by rafaesc** [comment]
Hi there, Can you create an example to review it?

**Comment by elevatebart** [comment]
It is cause by the upgrade of vue-dcgen-api to babel 7. Vue styleguidist sued to able to compile .vue files that had dependencies. It seems to be broken now.
For instance the following menu will fail. 

```vue
<template>
<div>
{{profileName}}
<CustomMenu/>
</div>
</template>
<script>
import CustomMenu from "./CustomMenu";

export default {
name: "nav-bar",
components:{CustomMenu}
}
</script>
```
I believe it's a bug in `vue-docgen-api` and I have the same issue.
For now, I ignored all the components that had imports from the styleguide but it does not seem like a durable solution. 

@rafaesc to have a reproductible repo just open a comman prompt and type 
```bash
> npm install --global @vue/cli
> vue create test-bug --default
> cd test-bug
> vue add styleguidist
> npm run styleguide
```

The standard is failing

**Comment by elevatebart** [comment]
This looks like either a bug on babel or an incompatibility between the runtime and the core we have.
Anyway the first line
```js
import MyComp from './MyComp.vue';
``` 

is transformed into:
```js
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/es6/interopRequireDefault");
var _caretMenu = _interopRequireDefault(require("@molecules/caretMenu"));
```

but the code of interopRequireDefault exports a 'default', it is an es6 module. Therefore, it cannot be imported this way. 
I got it traced back to `@vue/cli-plugin-babel` who forces the beta 47 of babel 7 in the dependencies.

Good night.

**Comment by casio** [comment]
I can confirm @elevatebart fix is working in my vanilla project - nice, thx! : )

will test this in my production project as well and report back here

**Comment by rafaesc** [comment]
@casio I have already updated vue-docgen-api

Try to install the last version of `vue-docgen-api`

**Comment by elevatebart** [comment]
Hey @casio !
Can I close this then ? I am trying to clean up a little.

**Comment by casio** [comment]
Hey @elevatebart - yea sure, lets close this: just had another attempt with a vanilla setup and the issue is gone!

Unfortunately I wasnt yet able to try in my production env, but once I do I'll eventually add a new ticket.
Thanks again for checking back!

**Comment by f3ltron** [comment]
why close the examples folder are not updated all solutions are not working for me really boring...

**Comment by elevatebart** [comment]
Hello, salut,

If you had this issue cannot read property default of undefined, it either has to do with using the latest version of Babel. In order to optimize parsing of the documentation, vue docgen api evaluates thé component after replacing all requires by meaningless objects. 

It failing in a lot of cases flagged AST in docgen issues. I am working on a permanent solution in a PR. I will discuss this with @rafaesc.

Your issue and opinion is important to us. Hope you will enjoy the new version

**Comment by JessicaSachs** [comment]
Hi @elevatebart!

I'd really love to use this tool. It looks awesome!

However, I'm also having the "cannot read property default of undefined" issue. I'm using Babel v7 and trying to build the default example "AppButton" you ship in your getting started setup and get the same error. Babel v7 is now shipping with vue-cli by default, so I think supporting it is necessary.

I was able to work around the issue by changing AppButton.vue file to
``` javascript
// fixed
const sizeMixin = require('./sizeMixin');

// broken
import sizeMixin from './sizeMixin';
```

This makes sense to me because `sizeMixin` is using `module.exports` syntax.... _not_ `export default` syntax.

Can you please provide a timeline for when your PR will be merged? :-)

Thanks.

**Comment by elevatebart** [comment]
I am desperately waiting for @rafaesc review. 
Given the popular demand, :) I might very well merge it next Sunday. 

@rafaesc if you can review vue-styleguidist/vue-docgen-api#68 please just click on merge. ;)

Bart Ledoux
Twitter: @bartledoux
Github: @elevatebart
